#!/bin/bash
set -euo pipefail

# ─── Spec-Driven Development Pipeline ───────────────────────────
# Orchestrates three LLM agents through a seven-phase development loop.
#
# CACHE OPTIMISATION: Claude Code invocations are structured to
# maximise prompt cache hits:
#   Session A1: merge tests + generate plan (cold start)
#   Session A2: revise plan based on reviews (--continue reuses cache)
#   Session B1: implement (cold start)
#   Session B2: fix adversarial failures (--continue reuses cache)
# The stable prefix (CONTEXT.md + CLAUDE.md + tool definitions) is
# paid once per cold start, then read from cache at 90% discount
# for continued sessions.
#
# CONTEXT.md: A single file combining all project docs and codebase
# state. Generated by a pure shell script (no LLM cost). All agents
# read this one file instead of scanning multiple doc files separately.
#
# Usage:
#   ./scripts/dev-loop.sh <feature-name>              # Full pipeline
#   ./scripts/dev-loop.sh <feature-name> --from 2     # Start from phase 2
#   ./scripts/dev-loop.sh <feature-name> --only 0     # Run single phase
#   ./scripts/dev-loop.sh <feature-name> --force       # Skip complexity halts
# ─────────────────────────────────────────────────────────────────

# ─── Configuration ───────────────────────────────────────────────
# Timeout for each agent invocation (seconds). Override with env var.
AGENT_TIMEOUT="${AGENT_TIMEOUT:-3600}"  # 60 minutes default

# ─── Parse arguments ─────────────────────────────────────────────
FEATURE="${1:?Usage: ./scripts/dev-loop.sh <feature-name> [--from N] [--only N] [--force]}"
shift

FROM_PHASE=0
ONLY_PHASE=-1
FORCE=false

while [[ $# -gt 0 ]]; do
    case $1 in
        --from) FROM_PHASE="$2"; shift 2 ;;
        --only) ONLY_PHASE="$2"; shift 2 ;;
        --force) FORCE=true; shift ;;
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
done

SPEC_FILE="specs/${FEATURE}.md"
PLAN_FILE="plans/${FEATURE}-plan.md"
PLAN_DONE="plans/${FEATURE}-plan.done"
PLAN_GEMINI="reviews/plan-reviews/${FEATURE}-gemini.md"
PLAN_QWEN="reviews/plan-reviews/${FEATURE}-qwen.md"
REVIEW_FILE="reviews/adversarial/${FEATURE}-review.md"
IMPL_DONE=".pipeline/${FEATURE}-impl.done"
TIMESTAMP=$(date +%Y%m%d-%H%M%S)
LOG_FILE="logs/${FEATURE}-${TIMESTAMP}.log"

# Session IDs for Claude --continue
SESSION_A_ID=""
SESSION_B_ID=""

# ─── Validation ──────────────────────────────────────────────────
if [ ! -f "$SPEC_FILE" ]; then
    echo "Error: spec file $SPEC_FILE not found"
    echo "Create one with: cp specs/_template.md $SPEC_FILE"
    exit 1
fi

mkdir -p logs reviews/spec-critiques reviews/plan-reviews reviews/adversarial \
         tests/gemini tests/qwen tests/adversarial tests/merged plans .pipeline

# ─── Read complexity thresholds from config ──────────────────────
MAX_SCREENS=4
MAX_COMPONENTS=5
MAX_API_ENDPOINTS=3
MAX_MODIFIED_FILES=10
MAX_CODE_LINES=500
MAX_TESTS=50

if [ -f "pipeline.config.json" ] && command -v node &> /dev/null; then
    eval "$(node -e "
const c = require('./pipeline.config.json').complexity || {};
console.log('MAX_SCREENS=' + (c.maxScreens || 4));
console.log('MAX_COMPONENTS=' + (c.maxNewComponents || 5));
console.log('MAX_API_ENDPOINTS=' + (c.maxNewApiEndpoints || 3));
console.log('MAX_MODIFIED_FILES=' + (c.maxModifiedFiles || 10));
console.log('MAX_CODE_LINES=' + (c.maxNewCodeLines || 500));
console.log('MAX_TESTS=' + (c.maxTests || 50));
" 2>/dev/null)" || true
fi

# ─── Logging ─────────────────────────────────────────────────────
exec > >(tee -a "$LOG_FILE") 2>&1
echo "Pipeline started: $(date)"
echo "Feature: $FEATURE"
echo "Log: $LOG_FILE"

# ─── Git branch ──────────────────────────────────────────────────
CURRENT_BRANCH=$(git branch --show-current)
if [[ "$CURRENT_BRANCH" != feat/${FEATURE}* ]]; then
    echo "Creating branch feat/${FEATURE}..."
    git checkout -b "feat/${FEATURE}" 2>/dev/null || git checkout "feat/${FEATURE}"
fi

# ─── Git checkpoint for rollback ─────────────────────────────────
CHECKPOINT_SHA=$(git rev-parse HEAD)
echo "Checkpoint: $CHECKPOINT_SHA (use 'git reset --hard $CHECKPOINT_SHA' to rollback)"

# ─── Generate fresh CONTEXT.md ───────────────────────────────────
echo ""
echo "Generating fresh CONTEXT.md for this pipeline run..."
if [ -f "./scripts/generate-context.sh" ]; then
    ./scripts/generate-context.sh
fi

# ─── Agent runner with timeout ───────────────────────────────────
# Wraps an agent invocation with a timeout. Captures exit code.
# Usage: run_agent <name> <timeout_seconds> <command...>
run_agent() {
    local name="$1"
    local agent_timeout="$2"
    shift 2

    echo "  Starting $name (timeout: ${agent_timeout}s)..."
    if timeout "$agent_timeout" "$@"; then
        echo "  ✓ $name completed successfully."
        return 0
    else
        local exit_code=$?
        if [ $exit_code -eq 124 ]; then
            echo "  ✗ $name TIMED OUT after ${agent_timeout}s."
        else
            echo "  ✗ $name FAILED with exit code $exit_code."
        fi
        return $exit_code
    fi
}

# ─── Complexity check helper ─────────────────────────────────────
check_complexity() {
    local output_file="$1"
    local phase_name="$2"

    if [ -f "$output_file" ] && grep -q "COMPLEXITY_LIMIT" "$output_file" 2>/dev/null; then
        echo ""
        echo "========================================================"
        echo "  ⚠  COMPLEXITY LIMIT — Feature flagged as too large"
        echo "========================================================"
        echo ""
        echo "  Detected in: $phase_name"
        echo "  Decomposition: specs/${FEATURE}-decomposition.md"
        echo ""
        echo "  To work on sub-tasks instead:"
        echo "    1. Review the decomposition file"
        echo "    2. Create specs for each sub-task"
        echo "    3. Run: ./scripts/dev-loop.sh <sub-task-name>"
        echo ""

        if [ "$FORCE" = true ]; then
            echo "  --force flag set. Continuing anyway (not recommended)."
            echo ""
        else
            echo "  To proceed anyway (not recommended):"
            echo "    ./scripts/dev-loop.sh ${FEATURE} --force"
            echo ""
            exit 0
        fi
    fi
}

# ─── Helper: should run phase? ───────────────────────────────────
should_run() {
    local phase=$1
    if [ "$ONLY_PHASE" -ge 0 ]; then
        [ "$phase" -eq "$ONLY_PHASE" ]
    else
        [ "$phase" -ge "$FROM_PHASE" ]
    fi
}

# ─── Helper: require phase success ───────────────────────────────
# Checks that a required file exists before continuing.
require_file() {
    local file="$1"
    local description="$2"
    if [ ! -f "$file" ]; then
        echo ""
        echo "  ✗ ERROR: $description not found at $file"
        echo "  The previous phase may have failed. Check the log for details."
        echo "  Aborting pipeline."
        exit 1
    fi
}


# ═════════════════════════════════════════════════════════════════
# PHASE 0 — Spec Hardening (Gemini + Qwen, parallel, free)
# ═════════════════════════════════════════════════════════════════
if should_run 0; then
    echo ""
    echo "══════════════════════════════════════════════════"
    echo "  Phase 0 — Spec Hardening"
    echo "══════════════════════════════════════════════════"

    GEMINI_OUT="reviews/spec-critiques/${FEATURE}-gemini.md"
    QWEN_OUT="reviews/spec-critiques/${FEATURE}-qwen.md"

    echo "[0/6] Running Gemini + Qwen in parallel..."

    GEMINI_EXIT=0
    QWEN_EXIT=0

    timeout "$AGENT_TIMEOUT" gemini -p "
Read CONTEXT.md for full project state.
Read the feature spec at ${SPEC_FILE}.
Read GEMINI.md for your role and instructions.

FIRST, assess whether this feature is too complex for a single pipeline run.
Read pipeline.config.json for complexity thresholds. A feature is too complex
if it exceeds any of: ${MAX_SCREENS} screens, ${MAX_COMPONENTS} new components,
${MAX_API_ENDPOINTS} API endpoints, ${MAX_MODIFIED_FILES} modified files,
${MAX_CODE_LINES} lines of new code, or contains independently-shippable parts.

If too complex: output COMPLEXITY_LIMIT: This feature should be split.
Generate a decomposition to specs/${FEATURE}-decomposition.md. Stop.

If not too complex: critique the spec for missing error states, unspecified
technical constraints, accessibility gaps, conflicts with existing architecture,
and ambiguous wording. Save to ${GEMINI_OUT}.
" --yolo > /tmp/gemini-phase0.out 2>&1 &
    GEMINI_PID=$!

    timeout "$AGENT_TIMEOUT" qwen -p "
Read CONTEXT.md for full project state.
Read the feature spec at ${SPEC_FILE}.
Read AGENTS.md for your role and instructions.

FIRST, assess whether this feature is too complex for a single pipeline run.
Read pipeline.config.json for complexity thresholds. A feature is too complex
if it exceeds any of: ${MAX_SCREENS} screens, ${MAX_COMPONENTS} new components,
${MAX_API_ENDPOINTS} API endpoints, ${MAX_MODIFIED_FILES} modified files,
${MAX_CODE_LINES} lines of new code, or contains independently-shippable parts.

If too complex: output COMPLEXITY_LIMIT: This feature should be split.
Generate a decomposition to specs/${FEATURE}-decomposition.md. Stop.

If not too complex: critique the spec for ambiguous user flows, boundary
conditions, race conditions, and cases where two developers would implement
differently. Save to ${QWEN_OUT}.
" -y > /tmp/qwen-phase0.out 2>&1 &
    QWEN_PID=$!

    wait $GEMINI_PID || GEMINI_EXIT=$?
    wait $QWEN_PID || QWEN_EXIT=$?

    if [ $GEMINI_EXIT -ne 0 ]; then
        echo "  ⚠ Gemini exited with code $GEMINI_EXIT"
    fi
    if [ $QWEN_EXIT -ne 0 ]; then
        echo "  ⚠ Qwen exited with code $QWEN_EXIT"
    fi

    # Only check complexity after both agents have finished
    check_complexity /tmp/gemini-phase0.out "Phase 0 — Gemini spec review"
    check_complexity /tmp/qwen-phase0.out "Phase 0 — Qwen spec review"

    echo ""
    echo "  Spec critiques ready:"
    [ -f "$GEMINI_OUT" ] && echo "    - $GEMINI_OUT" || echo "    - $GEMINI_OUT (missing — Gemini may have failed)"
    [ -f "$QWEN_OUT" ] && echo "    - $QWEN_OUT" || echo "    - $QWEN_OUT (missing — Qwen may have failed)"
    echo ""
    read -p "  Review both, update your spec, then press Enter to continue (or Ctrl+C to stop)..."
fi


# ═════════════════════════════════════════════════════════════════
# PHASE 1 — Test Generation (Gemini + Qwen, parallel, free)
# ═════════════════════════════════════════════════════════════════
if should_run 1; then
    echo ""
    echo "══════════════════════════════════════════════════"
    echo "  Phase 1 — Test Generation"
    echo "══════════════════════════════════════════════════"

    echo "[1/6] Running Gemini (breadth) + Qwen (adversarial) in parallel..."

    GEMINI_EXIT=0
    QWEN_EXIT=0

    timeout "$AGENT_TIMEOUT" gemini -p "
Read CONTEXT.md for full project state.
Read the feature spec at ${SPEC_FILE}.
Read GEMINI.md for your role and instructions.

Write comprehensive tests for this feature. Save to tests/gemini/.
Focus: happy paths, component rendering, accessibility, responsive, state transitions.
After writing, run them once to verify they compile (failures expected).
" --yolo &
    GEMINI_PID=$!

    timeout "$AGENT_TIMEOUT" qwen -p "
Read CONTEXT.md for full project state.
Read the feature spec at ${SPEC_FILE}.
Read AGENTS.md for your role and instructions.

Write adversarial tests for this feature. Save to tests/qwen/.
Focus: error states, empty/null data, boundary values, rapid interaction,
network failures, malformed data, concurrent state changes.
After writing, run them once to verify they compile.
" -y &
    QWEN_PID=$!

    wait $GEMINI_PID || GEMINI_EXIT=$?
    wait $QWEN_PID || QWEN_EXIT=$?

    if [ $GEMINI_EXIT -ne 0 ]; then
        echo "  ⚠ Gemini exited with code $GEMINI_EXIT"
    fi
    if [ $QWEN_EXIT -ne 0 ]; then
        echo "  ⚠ Qwen exited with code $QWEN_EXIT"
    fi

    echo "  Phase 1 complete. Tests in tests/gemini/ and tests/qwen/."
fi


# ═════════════════════════════════════════════════════════════════
# PHASE 2 — Planning (Claude Session A)
# ═════════════════════════════════════════════════════════════════
#
# Cache strategy: CONTEXT.md + CLAUDE.md form the stable prefix.
# Session A1 (merge + plan) writes to cache. Session A2 (revise)
# uses --continue to reuse the warm cache at 90% discount.
#
# FIX: The original design tried to run all three tasks in a single
# backgrounded Claude invocation, expecting Claude to "pause" and
# wait for Gemini/Qwen reviews. Claude -p cannot pause — it runs
# straight through. Now we split into two sequential invocations
# (A1 and A2), with Gemini/Qwen reviews running between them.
# ═════════════════════════════════════════════════════════════════
if should_run 2; then
    echo ""
    echo "══════════════════════════════════════════════════"
    echo "  Phase 2 — Merge + Plan + Review + Revise"
    echo "══════════════════════════════════════════════════"

    # ── Session A1: Merge tests + generate plan ──────────────────
    echo "  [2a/6] Claude: Merging test suites and generating plan..."

    run_agent "Claude Session A1" "$AGENT_TIMEOUT" \
        claude -p "
Read CONTEXT.md for full project state. Read CLAUDE.md for your instructions.

You have TWO tasks in this session.

───────────────────────────────────────────────────
TASK 1: Merge test suites
───────────────────────────────────────────────────
Two independently-generated test suites exist:
- tests/gemini/ — breadth tests (happy paths, accessibility)
- tests/qwen/ — adversarial tests (failures, edge cases)

Merge into tests/merged/:
1. Read every test file in both directories
2. Deduplicate (keep the more thorough version of overlapping tests)
3. Resolve naming conflicts
4. Fix all imports for consistency

Run tests to verify compilation (failures expected — no implementation yet).
Fix compilation errors only. Do NOT write implementation code.
Report: total test count and brief coverage summary.

───────────────────────────────────────────────────
TASK 2: Generate implementation plan
───────────────────────────────────────────────────
Read the feature spec at ${SPEC_FILE}.
Read the merged test suite in tests/merged/.

FIRST assess complexity using these thresholds from pipeline.config.json:
- Max tests: ${MAX_TESTS}
- Max new files: 8
- Max new code lines: ${MAX_CODE_LINES}
- Max independent concerns: 2

If the feature exceeds these limits:
  Output COMPLEXITY_LIMIT: This feature should be split.
  Generate decomposition to specs/${FEATURE}-decomposition.md. Stop entirely.

Otherwise, generate an implementation plan to ${PLAN_FILE} covering:
- Files to create or modify (one-line description each)
- Component hierarchy (what renders what, key props)
- State management (which stores, state shape, data flow)
- New types or interfaces needed
- Integration points with existing code
- Implementation order (dependency-based)
- Risk areas (complex logic, performance, tricky CSS)

Do NOT write implementation code. Blueprint only.

When BOTH tasks are complete, create a signal file:
  echo 'done' > ${PLAN_DONE}
" --dangerously-skip-permissions 2>&1 | tee /tmp/claude-sessionA1.out

    # Extract session ID for --continue
    SESSION_A_ID=$(grep -o 'session_id=[^ ]*' /tmp/claude-sessionA1.out 2>/dev/null | tail -1 | cut -d= -f2 || true)

    check_complexity /tmp/claude-sessionA1.out "Session A1 — Claude plan generation"
    require_file "$PLAN_FILE" "Implementation plan"

    # ── Gemini + Qwen plan reviews (parallel, free) ──────────────
    echo ""
    echo "  [2b/6] Plan generated. Running Gemini + Qwen reviews..."

    GEMINI_EXIT=0
    QWEN_EXIT=0

    timeout "$AGENT_TIMEOUT" gemini -p "
Read CONTEXT.md for full project state. Read GEMINI.md for your role and instructions.
Read the implementation plan at ${PLAN_FILE}.

Review for: architectural consistency with existing patterns, unnecessary
complexity, missed integration points, reusable existing components.
Save to ${PLAN_GEMINI}.
" --yolo &
    GEMINI_PID=$!

    timeout "$AGENT_TIMEOUT" qwen -p "
Read CONTEXT.md for full project state. Read AGENTS.md for your role and instructions.
Read ${PLAN_FILE}, ${SPEC_FILE}, and tests/merged/.

Review for: over-engineering, missing error handling paths, unnecessary
state complexity, test scenarios the plan does not address.
Save to ${PLAN_QWEN}.
" -y &
    QWEN_PID=$!

    wait $GEMINI_PID || GEMINI_EXIT=$?
    wait $QWEN_PID || QWEN_EXIT=$?

    if [ $GEMINI_EXIT -ne 0 ]; then
        echo "  ⚠ Gemini plan review exited with code $GEMINI_EXIT"
    fi
    if [ $QWEN_EXIT -ne 0 ]; then
        echo "  ⚠ Qwen plan review exited with code $QWEN_EXIT"
    fi

    echo "  Plan reviews complete."

    # ── Session A2: Revise plan based on reviews ─────────────────
    echo ""
    echo "  [2c/6] Claude: Revising plan based on reviews..."

    # Build the revision prompt
    REVISION_PROMPT="
Read the plan reviews:
- ${PLAN_GEMINI}
- ${PLAN_QWEN}

Revise ${PLAN_FILE} based on these reviews:
- Address valid feedback by updating the plan
- For feedback you disagree with, add a note explaining why
- Add a '## Revision Notes' section at the end

Report what you changed.
"
    # Try --continue if we have a session ID, otherwise start fresh
    if [ -n "$SESSION_A_ID" ]; then
        run_agent "Claude Session A2 (continue)" "$AGENT_TIMEOUT" \
            claude -p "$REVISION_PROMPT" --continue "$SESSION_A_ID" --dangerously-skip-permissions \
            2>&1 | tee /tmp/claude-sessionA2.out || \
        run_agent "Claude Session A2 (fresh)" "$AGENT_TIMEOUT" \
            claude -p "Read CONTEXT.md. Read CLAUDE.md. $REVISION_PROMPT" --dangerously-skip-permissions \
            2>&1 | tee /tmp/claude-sessionA2.out
    else
        run_agent "Claude Session A2 (fresh)" "$AGENT_TIMEOUT" \
            claude -p "Read CONTEXT.md. Read CLAUDE.md. $REVISION_PROMPT" --dangerously-skip-permissions \
            2>&1 | tee /tmp/claude-sessionA2.out
    fi

    echo ""
    echo "  Plan ready: $PLAN_FILE"
    [ -f "$PLAN_GEMINI" ] && echo "  Reviews:    $PLAN_GEMINI"
    [ -f "$PLAN_QWEN" ] && echo "              $PLAN_QWEN"
    echo ""
    read -p "  Review the plan, then press Enter to implement (or Ctrl+C to stop)..."
fi


# ═════════════════════════════════════════════════════════════════
# PHASE 3 — Implementation (Claude Session B1)
# ═════════════════════════════════════════════════════════════════
if should_run 3; then
    echo ""
    echo "══════════════════════════════════════════════════"
    echo "  Phase 3 — Implementation"
    echo "══════════════════════════════════════════════════"

    echo "  [3/6] Implementing feature..."

    run_agent "Claude Session B1 (implement)" "$AGENT_TIMEOUT" \
        claude -p "
Read CONTEXT.md for full project state. Read CLAUDE.md for your instructions.

───────────────────────────────────────────────────
Implement the feature
───────────────────────────────────────────────────
Read the feature spec at ${SPEC_FILE}.
Read the implementation plan at ${PLAN_FILE}.
Read the merged test suite in tests/merged/.

Before implementing: if at any point you find the scope exceeds
single-session capacity or you are making quality compromises
(skipping error handling, writing placeholder code, losing track of
state across files), STOP. Output COMPLEXITY_LIMIT and save a partial
decomposition to specs/${FEATURE}-decomposition.md showing what is
complete and what remains.

Otherwise: implement following the plan exactly.
- Create files in the order specified in the plan
- Follow the component hierarchy and state approach
- Run tests after each file or logical group of files
- Fix implementation (NEVER modify tests) until all pass

Once all tests pass, commit:
  git add -A
  git commit -m 'feat(${FEATURE}): implement feature'

Then create a signal file:
  echo 'done' > ${IMPL_DONE}

Report: total tests passing, files created/modified.
" --dangerously-skip-permissions 2>&1 | tee /tmp/claude-sessionB1.out

    # Extract session ID for --continue in Phase 4
    SESSION_B_ID=$(grep -o 'session_id=[^ ]*' /tmp/claude-sessionB1.out 2>/dev/null | tail -1 | cut -d= -f2 || true)

    check_complexity /tmp/claude-sessionB1.out "Session B1 — Claude implementation"

    # Verify implementation succeeded
    if [ ! -f "$IMPL_DONE" ]; then
        echo ""
        echo "  ⚠ Implementation signal file not found."
        echo "  Claude may have failed or hit complexity limits."
        echo "  Check /tmp/claude-sessionB1.out for details."
        echo ""
        if [ "$FORCE" != true ]; then
            echo "  Use --force to continue anyway, or fix and restart with --from 3"
            exit 1
        fi
    fi

    # ── Quality gates (hard failures) ────────────────────────────
    echo ""
    echo "  Running quality gates..."

    QUALITY_PASS=true

    # Test gate
    if ! npm test 2>&1; then
        echo "  ✗ TESTS FAILED"
        QUALITY_PASS=false
    else
        echo "  ✓ Tests pass"
    fi

    # Lint gate
    LINT_CMD=$(node -e "const c=require('./pipeline.config.json');console.log(c.commands?.lint||'')" 2>/dev/null || true)
    if [ -n "$LINT_CMD" ]; then
        if ! eval "$LINT_CMD" 2>&1; then
            echo "  ✗ LINT FAILED"
            QUALITY_PASS=false
        else
            echo "  ✓ Lint passes"
        fi
    fi

    # Type check gate
    if [ -f "tsconfig.json" ]; then
        TYPECHECK_CMD=$(node -e "const c=require('./pipeline.config.json');console.log(c.commands?.typeCheck||'npx tsc --noEmit')" 2>/dev/null || echo "npx tsc --noEmit")
        if ! eval "$TYPECHECK_CMD" 2>&1; then
            echo "  ✗ TYPE CHECK FAILED"
            QUALITY_PASS=false
        else
            echo "  ✓ Type check passes"
        fi
    fi

    if [ "$QUALITY_PASS" = false ] && [ "$FORCE" != true ]; then
        echo ""
        echo "  ⚠ Quality gates failed. Fix issues before proceeding."
        echo "  Use --force to skip quality gates, or fix and restart with --from 3"
        exit 1
    fi
fi


# ═════════════════════════════════════════════════════════════════
# PHASE 4 — Adversarial Review (Qwen → Claude Session B2)
# ═════════════════════════════════════════════════════════════════
if should_run 4; then
    echo ""
    echo "══════════════════════════════════════════════════"
    echo "  Phase 4 — Adversarial Review + Fix"
    echo "══════════════════════════════════════════════════"

    # ── Qwen adversarial review ──────────────────────────────────
    echo "  [4a/6] Running Qwen adversarial review..."

    QWEN_EXIT=0
    run_agent "Qwen adversarial review" "$AGENT_TIMEOUT" \
        qwen -p "
Read CONTEXT.md for full project state.
Read AGENTS.md for your role and instructions.
Read ${SPEC_FILE} and ${PLAN_FILE}.
Read every file in src/ that was created or modified for this feature.
Read every test in tests/merged/.

Find: spec compliance issues, security concerns (XSS, data exposure),
robustness gaps (missing error handling, race conditions, cleanup),
accessibility issues (missing ARIA, keyboard traps).

Write additional tests to tests/adversarial/.
Save review summary to ${REVIEW_FILE}.
Do NOT modify any files in src/.
" -y 2>&1 | tee /tmp/qwen-phase4.out || QWEN_EXIT=$?

    if [ $QWEN_EXIT -ne 0 ]; then
        echo "  ⚠ Qwen adversarial review exited with code $QWEN_EXIT"
    fi

    # ── Claude fix adversarial failures ──────────────────────────
    echo ""
    echo "  [4b/6] Claude: Fixing adversarial review failures..."

    FIX_PROMPT="
Read the adversarial review at ${REVIEW_FILE}.
Read the new adversarial tests in tests/adversarial/.

Run ALL tests (tests/merged/ and tests/adversarial/).
If any new tests fail, fix the implementation in src/.
NEVER modify or delete any tests.

After all tests pass, commit:
  git add -A
  git commit -m 'fix(${FEATURE}): address adversarial review'

Report: which adversarial tests failed, what you changed.
"

    if [ -n "$SESSION_B_ID" ]; then
        run_agent "Claude Session B2 (continue)" "$AGENT_TIMEOUT" \
            claude -p "$FIX_PROMPT" --continue "$SESSION_B_ID" --dangerously-skip-permissions \
            2>&1 | tee /tmp/claude-sessionB2.out || \
        run_agent "Claude Session B2 (fresh)" "$AGENT_TIMEOUT" \
            claude -p "Read CONTEXT.md. Read CLAUDE.md. $FIX_PROMPT" --dangerously-skip-permissions \
            2>&1 | tee /tmp/claude-sessionB2.out
    else
        run_agent "Claude Session B2 (fresh)" "$AGENT_TIMEOUT" \
            claude -p "Read CONTEXT.md. Read CLAUDE.md. $FIX_PROMPT" --dangerously-skip-permissions \
            2>&1 | tee /tmp/claude-sessionB2.out
    fi

    [ -f "$REVIEW_FILE" ] && echo "  Adversarial review: $REVIEW_FILE"
fi


# ═════════════════════════════════════════════════════════════════
# PHASE 5 — Documentation (Gemini, free)
# ═════════════════════════════════════════════════════════════════
if should_run 5; then
    echo ""
    echo "══════════════════════════════════════════════════"
    echo "  Phase 5 — Documentation"
    echo "══════════════════════════════════════════════════"

    echo "[5/6] Gemini updating docs..."

    GEMINI_EXIT=0
    run_agent "Gemini documentation" "$AGENT_TIMEOUT" \
        gemini -p "
Read CONTEXT.md for full project state. Read GEMINI.md for your role and instructions.
Read plans/${FEATURE}-plan.md. Scan src/ for changes.

Update these doc files with any changes from this feature:
- docs/ARCHITECTURE.md — new directories, components, data flows
- docs/DATA-MODEL.md — new TypeScript interfaces or type changes
- docs/DEPENDENCIES.md — new packages installed
- docs/DECISIONS.md — new architectural decisions (leave Reasoning blank)

Do NOT remove existing content unless factually incorrect.
Commit: git add docs/ && git commit -m 'docs(${FEATURE}): update documentation'
" --yolo || GEMINI_EXIT=$?

    if [ $GEMINI_EXIT -ne 0 ]; then
        echo "  ⚠ Gemini documentation exited with code $GEMINI_EXIT"
    fi

    echo "  Phase 5 complete."
fi


# ═════════════════════════════════════════════════════════════════
# PHASE 6 — Context Regeneration (pure shell, no LLM cost)
# ═════════════════════════════════════════════════════════════════
if should_run 6; then
    echo ""
    echo "══════════════════════════════════════════════════"
    echo "  Phase 6 — Context Regeneration"
    echo "══════════════════════════════════════════════════"

    echo "[6/6] Regenerating CONTEXT.md with final state..."

    ./scripts/generate-context.sh

    echo "  Phase 6 complete."
fi


# ═════════════════════════════════════════════════════════════════
# Cleanup
# ═════════════════════════════════════════════════════════════════
rm -f "$PLAN_DONE" "$IMPL_DONE" 2>/dev/null || true


# ═════════════════════════════════════════════════════════════════
# Summary
# ═════════════════════════════════════════════════════════════════
echo ""
echo "══════════════════════════════════════════════════"
echo "  Pipeline complete: $FEATURE"
echo "══════════════════════════════════════════════════"
echo ""
echo "  Artifacts:"
echo "    Spec:              $SPEC_FILE"
echo "    Spec critiques:    reviews/spec-critiques/"
echo "    Tests:             tests/merged/ + tests/adversarial/"
echo "    Plan:              $PLAN_FILE"
echo "    Plan reviews:      reviews/plan-reviews/"
echo "    Adversarial review: $REVIEW_FILE"
echo "    Context:           CONTEXT.md"
echo "    Log:               $LOG_FILE"
echo ""
echo "  Rollback: git reset --hard $CHECKPOINT_SHA"
echo ""
echo "  Git log:"
git log --oneline -10
echo ""
echo "  Your turn: review the diff, check the UI in browser,"
echo "  and decide whether to merge or iterate."
echo ""
